# Generated by Django 3.0.4 on 2021-09-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbRecoveryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EnvCreateOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FaultResolveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='工单号', max_length=30, unique=True, verbose_name='工单号')),
                ('title', models.CharField(help_text='工单标题', max_length=30, unique=True, verbose_name='工单标题')),
                ('content', models.CharField(help_text='工单内容', max_length=30, unique=True, verbose_name='工单内容')),
                ('type', models.CharField(choices=[('1', '环境申请'), ('2', '数据恢复'), ('3', '故障处理'), ('4', '服务请求')], default='0', help_text='工单类型', max_length=30, verbose_name='工单类型')),
                ('status', models.CharField(choices=[('1', '待提交'), ('2', '待审核'), ('3', '执行中'), ('4', '待脱敏'), ('5', '脱敏中'), ('6', '已脱敏'), ('7', '待确认'), ('8', '已关闭')], default='0', help_text='工单状态', max_length=30, verbose_name='工单状态')),
                ('is_show', models.BooleanField(blank=True, default=True, verbose_name='是否显示')),
                ('is_return', models.BooleanField(blank=True, default=True, verbose_name='是否退回')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('expect_time', models.DateTimeField(blank=True, null=True, verbose_name='期望时间')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('target_time', models.DateTimeField(blank=True, null=True, verbose_name='目标时间')),
            ],
        ),
    ]
