# Generated by Django 3.0.4 on 2021-09-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210909_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['number'], 'verbose_name': '工单信息', 'verbose_name_plural': '工单信息'},
        ),
    ]
