# Generated by Django 3.0.4 on 2021-09-30 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0003_auto_20210910_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvCreateDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(blank=True, help_text='项目编号', max_length=30, null=True, verbose_name='项目编号')),
                ('requirement_number', models.CharField(blank=True, help_text='需求编号', max_length=30, null=True, verbose_name='需求编号')),
                ('file_content_resource', models.FileField(blank=True, help_text='资源规划表', null=True, upload_to='file/%Y/%m/%d', verbose_name='资源规划表')),
                ('file_content_request', models.FileField(blank=True, help_text='资源申请表', null=True, upload_to='file/%Y/%m/%d', verbose_name='资源申请表')),
                ('is_standard', models.BooleanField(blank=True, default=False, help_text='是否标准交付', null=True, verbose_name='是否标准交付')),
                ('linkman', models.ForeignKey(blank=True, help_text='接口人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_man', to=settings.AUTH_USER_MODEL, verbose_name='接口人')),
            ],
            options={
                'verbose_name': '环境新建详情',
                'verbose_name_plural': '环境新建详情',
            },
        ),
        migrations.CreateModel(
            name='SubWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='子工单号', max_length=30, unique=True, verbose_name='子工单号')),
                ('status', models.CharField(choices=[('1', '新建待提交'), ('2', '处理中'), ('3', '已完成'), ('4', '已关闭')], default='0', help_text='子工单状态', max_length=30, verbose_name='子工单状态')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('content', models.TextField(blank=True, help_text='工单内容', null=True, verbose_name='工单内容')),
                ('execution', models.TextField(blank=True, help_text='完成情况', null=True, verbose_name='工单内容')),
                ('initiator', models.ForeignKey(blank=True, help_text='发起人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiator', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '子工单信息',
                'verbose_name_plural': '子工单信息',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderDeliverRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('name', models.ForeignKey(blank=True, help_text='交付人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='交付人')),
            ],
            options={
                'verbose_name': '交付记录',
                'verbose_name_plural': '交付记录',
            },
        ),
        migrations.DeleteModel(
            name='EnvCreateOrder',
        ),
        migrations.AlterModelOptions(
            name='faultresolveorder',
            options={'verbose_name': '故障解决详情', 'verbose_name_plural': '故障解决详情'},
        ),
        migrations.AddField(
            model_name='dbrecoveryorder',
            name='data_extract_list',
            field=models.FileField(blank=True, help_text='数据提取单', null=True, upload_to='file/%Y/%m/%d', verbose_name='数据提取单'),
        ),
        migrations.AddField(
            model_name='dbrecoveryorder',
            name='oa_info_list',
            field=models.FileField(blank=True, help_text='oa稿签表', null=True, upload_to='file/%Y/%m/%d', verbose_name='oa稿签表'),
        ),
        migrations.AddField(
            model_name='dbrecoveryorder',
            name='oa_number',
            field=models.CharField(blank=True, help_text='OA编号', max_length=20, null=True, verbose_name='OA编号'),
        ),
        migrations.AddField(
            model_name='dbrecoveryorder',
            name='redata_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='脱敏开始时间 1'),
        ),
        migrations.AddField(
            model_name='dbrecoveryorder',
            name='safeman',
            field=models.ForeignKey(blank=True, help_text='脱敏审核人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safeman', to=settings.AUTH_USER_MODEL, verbose_name='脱敏审核人'),
        ),
        migrations.AddField(
            model_name='dbrecoveryorder',
            name='sensitive_info_form',
            field=models.FileField(blank=True, help_text='敏感信息表', null=True, upload_to='file/%Y/%m/%d', verbose_name='敏感信息表'),
        ),
        migrations.AddField(
            model_name='dbrecoveryorder',
            name='sensitive_type',
            field=models.CharField(blank=True, choices=[('1', '有敏感信息-脱敏'), ('2', '有敏感信息-不脱敏'), ('3', '无敏感信息')], default='3', help_text='敏感信息类型', max_length=10, null=True, verbose_name='敏感信息类型'),
        ),
        migrations.AddField(
            model_name='faultresolveorder',
            name='cause',
            field=models.TextField(blank=True, help_text='根本类型', max_length=50, null=True, verbose_name='根本类型'),
        ),
        migrations.AddField(
            model_name='faultresolveorder',
            name='fault',
            field=models.CharField(blank=True, choices=[('1', '普通'), ('2', '紧急')], help_text='故障类型', max_length=10, null=True, verbose_name='故障类型'),
        ),
        migrations.AddField(
            model_name='faultresolveorder',
            name='hostenvs',
            field=models.CharField(blank=True, help_text='所有故障主机', max_length=500, null=True, verbose_name='所有故障主机'),
        ),
        migrations.AddField(
            model_name='faultresolveorder',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', '普通'), ('2', '紧急')], help_text='紧急程度', max_length=10, null=True, verbose_name='紧急程度'),
        ),
        migrations.AddField(
            model_name='faultresolveorder',
            name='screenshot',
            field=models.FileField(blank=True, help_text='故障截图', null=True, upload_to='file/%Y/%m/%d', verbose_name='故障截图'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='final_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approver', to=settings.AUTH_USER_MODEL, verbose_name='终审人'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='up_todoer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='up_todoer', to=settings.AUTH_USER_MODEL, verbose_name='上级处理人'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL, verbose_name='初审人'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='todoer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todoer', to=settings.AUTH_USER_MODEL, verbose_name='当前处理人'),
        ),
        migrations.AddField(
            model_name='workorderdeliverrecord',
            name='work_order',
            field=models.ForeignKey(help_text='所属工单', on_delete=django.db.models.deletion.CASCADE, to='personal.WorkOrder', verbose_name='所属工单'),
        ),
        migrations.AddField(
            model_name='subworkorder',
            name='work_order',
            field=models.ForeignKey(help_text='所属工单', on_delete=django.db.models.deletion.CASCADE, to='personal.WorkOrder', verbose_name='所属工单'),
        ),
    ]
