# Generated by Django 3.0.4 on 2021-09-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorderrole',
            options={'verbose_name': '工单角色', 'verbose_name_plural': '工单角色'},
        ),
        migrations.RemoveField(
            model_name='permission',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='role',
            name='menus',
        ),
        migrations.AddField(
            model_name='permission',
            name='menus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='管理菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='method',
            field=models.CharField(blank=True, choices=[('ALL', '*'), ('GET', 'GET'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('POST', 'POST'), ('DELETE', 'DELETE')], max_length=50, null=True, verbose_name='方法'),
        ),
    ]
