# Generated by Django 3.0.4 on 2021-09-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20210910_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorderrole',
            options={'ordering': ['id'], 'verbose_name': '工单角色', 'verbose_name_plural': '工单角色'},
        ),
        migrations.RemoveField(
            model_name='workorderrole',
            name='desc',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_linkman',
            field=models.BooleanField(default=True, verbose_name='是否接口人'),
        ),
        migrations.AddField(
            model_name='workorderrole',
            name='name_zh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='中文权限名'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='workorder_role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workorder_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.WorkorderRole', verbose_name='工单角色'),
        ),
        migrations.AlterField(
            model_name='workorderrole',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='权限名'),
        ),
    ]
